services:
  reply:
    build: .
    container_name: reply
    image: reply:latest
    ports:
      - 3000:3000
    volumes:
      - database:/app/data
      - uploads:/app/public/uploads
    networks:
      - demo

networks:
  demo:
    name: demo
    driver: bridge
    external: true

volumes:
  database:
  uploads:
